apiVersion : apps/v1
kind: Deployment
metadata:
  name: sohanazurelearn 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sohanazurelearn
  template:
    metadata:
      labels:
        app: sohanazurelearn 
    spec:
      initContainers:
      - name: import-gpg-key
        image: alpine:3.18.4
        command:
        - sh
        - -c
        - |
          apk add --no-cache gnupg &&
          ls -la /etc/gpg-keys &&
    
      containers:
        - name: sohanazurelearn 
          image: tstss.azurecr.io/custom2nginxapp
          ports:
          - containerPort: 80
          env:
          - name: MY_ENV_VAR
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: my-key
